// ═══════════════════════════════════════════════════
// SemioViz — i18n Translations
// ═══════════════════════════════════════════════════

const I18N = {
  it: {
    tagline: "Fondamenti della semiotica — Dall'equivalenza all'inferenza",
    search: "Cerca…",
    connsLabel: "Connessioni",
    agree: "accordo / sviluppo",
    disagree: "critica / opposizione",
    legendHint: "Clicca un'affermazione per vedere le connessioni",
    guideLabel: "Guida e info",
    filters: { all:"Tutto", segno:"Segno", significato:"Significato", epistemologia:"Epistemologia", forma:"Forma / Struttura", interpretazione:"Interpretazione", codice:"Codice", soggetto:"Soggettività", pragmatismo:"Pragmatismo", storia:"Ricostruzione storica" },
    authors: {
      precursors: { name:"Precursori", sub:"Ippocrate · Aristotele · Stoici · Agostino" },
      saussure: { name:"Saussure", sub:"Corso di linguistica generale (1916)" },
      peirce: { name:"Peirce", sub:"Saggi anti-cartesiani (1868) · pragmatisti (1877–78)" },
      hjelmslev: { name:"Hjelmslev", sub:"I fondamenti della teoria del linguaggio (1943)" },
      eco: { name:"Eco", sub:"Semiotica e filosofia del linguaggio (1984)" },
    },
    info: `
      <h2>SemioViz</h2>
      <p class="info-sub">Summarized & Visualized</p>
      <p class="info-tagline">Fondamenti della semiotica — Dall'equivalenza all'inferenza</p>
      <h3>Come funziona</h3>
      <p>Ogni <strong>colonna</strong> rappresenta un autore o corrente. Le <strong>card</strong> sono affermazioni sintetiche del suo pensiero. Clicca una card per aprire il dettaglio con spiegazione, diagramma e connessioni ad altre affermazioni.</p>
      <p>Usa i <strong>filtri</strong> in alto per esplorare per tema. Premi <kbd>Esc</kbd> o clicca fuori dal pannello per chiuderlo.</p>
      <div class="legend-row"><span class="legend-swatch" style="background:var(--green)"></span> <span>Connessione di accordo o sviluppo</span></div>
      <div class="legend-row"><span class="legend-swatch" style="background:var(--red)"></span> <span>Connessione di critica o opposizione</span></div>
      <div class="legend-row"><svg class="legend-icon" width="12" height="12" viewBox="0 0 16 16" fill="var(--text-dim)"><rect x="1" y="4" width="5" height="8" rx="1" opacity=".5"/><rect x="8" y="1" width="7" height="14" rx="1" opacity=".7"/></svg> <span>La card contiene un diagramma esplicativo</span></div>
      <h3>Il progetto</h3>
      <p>Una mappa interattiva che sintetizza e visualizza i concetti fondamentali della semiotica, seguendo il filo conduttore del passaggio dal <strong>modello ristretto</strong> (il segno come equivalenza) al <strong>modello allargato</strong> (il segno come inferenza). Circa 56 affermazioni sintetiche, oltre 90 connessioni, diagrammi ed esempi didattici.</p>
      <h3>Contribuisci</h3>
      <p>SemioViz è un progetto aperto: l'idea è partire da questo nucleo di autori e ampliarlo nel tempo con nuove correnti e teorie semiotiche. Contributi, suggerimenti e correzioni sono benvenuti su <a href="https://github.com/stefanocarotenuto/semio-viz" target="_blank" rel="noopener">GitHub</a>.</p>
      <h3>Riferimenti bibliografici</h3>
      <div class="refs">
        <div class="ref"><span class="ref-a">F. de Saussure</span><em>Corso di linguistica generale</em><span>(1916). Ed. it. Laterza.</span></div>
        <div class="ref"><span class="ref-a">L. Hjelmslev</span><em>I fondamenti della teoria del linguaggio</em><span>(1943). Ed. it. Einaudi, intr. G.C. Lepschy.</span></div>
        <div class="ref"><span class="ref-a">C.S. Peirce</span><em><a href="https://www.peirce.org/writings/p26.html" target="_blank" rel="noopener">Questions Concerning Certain Faculties Claimed for Man</a></em><span>(1868). Journal of Speculative Philosophy, 2.</span></div>
        <div class="ref"><span class="ref-a">C.S. Peirce</span><em><a href="https://www.peirce.org/writings/p27.html" target="_blank" rel="noopener">Some Consequences of Four Incapacities</a></em><span>(1868). Journal of Speculative Philosophy, 2.</span></div>
        <div class="ref"><span class="ref-a">C.S. Peirce</span><em><a href="https://www.peirce.org/writings/p107.html" target="_blank" rel="noopener">The Fixation of Belief</a></em><span>(1877). Popular Science Monthly, 12.</span></div>
        <div class="ref"><span class="ref-a">C.S. Peirce</span><em><a href="https://www.peirce.org/writings/p119.html" target="_blank" rel="noopener">How to Make Our Ideas Clear</a></em><span>(1878). Popular Science Monthly, 12.</span></div>
        <div class="ref"><span class="ref-a">U. Eco</span><em>Semiotica e filosofia del linguaggio</em><span>(1984). Einaudi. Cap. 1 (Segno e inferenza), 2 (Dizionario vs. Enciclopedia), 5 (Codice).</span></div>
      </div>
      <h3>Ispirazione</h3>
      <p>Visualizzazione ispirata a <a href="https://www.denizcemonduygu.com/philo/" target="_blank" rel="noopener">History of Philosophy — Summarized & Visualized</a> di Deniz Cem Önduygu.</p>
      <h3>Crediti immagini</h3>
      <p>I ritratti degli autori provengono da <a href="https://commons.wikimedia.org/" target="_blank" rel="noopener">Wikimedia Commons</a> e sono utilizzati nel rispetto delle rispettive licenze: busto di Aristotele (Palazzo Altemps, pubblico dominio), ritratto di Saussure di F. Jullien (pubblico dominio), ritratto di Peirce (pubblico dominio), ritratto di Eco (© Rob Bogaerts / Anefo, CC BY-SA 3.0 NL).</p>
      <p>Tipografia: Georgia (serif) e system-ui (sans-serif), font di sistema.</p>
      <div class="info-credits">
        <p>Progettazione e realizzazione: <a href="https://stefanocarotenuto.it" target="_blank" rel="noopener">Stefano Carotenuto</a></p>
        <p>Realizzato con l'assistenza di <a href="https://claude.com/claude-code" target="_blank" rel="noopener">Claude Code</a> di Anthropic.</p>
        <div class="info-license">
          <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener license">CC BY-NC-SA 4.0</a>
          <p>Libero per condivisione e adattamento a scopo non commerciale, con attribuzione e stessa licenza.</p>
        </div>
      </div>
      <div class="info-privacy">
        <h3>Privacy e Cookie</h3>
        <p>Questo sito è un'applicazione statica che funziona interamente nel browser. Non raccoglie dati personali, non utilizza cookie, non impiega servizi di tracciamento o analisi di terze parti. Nessun dato viene trasmesso a server esterni. La navigazione è completamente anonima.</p>
      </div>`,
    // No statement overrides needed — Italian is the default in S[]
    stmts: {}
  },

  en: {
    tagline: "Foundations of Semiotics — From Equivalence to Inference",
    search: "Search…",
    connsLabel: "Connections",
    agree: "agreement / development",
    disagree: "critique / opposition",
    legendHint: "Click a statement to see its connections",
    guideLabel: "Guide & info",
    filters: { all:"All", segno:"Sign", significato:"Meaning", epistemologia:"Epistemology", forma:"Form / Structure", interpretazione:"Interpretation", codice:"Code", soggetto:"Subjectivity", pragmatismo:"Pragmatism", storia:"Historical reconstruction" },
    authors: {
      precursors: { name:"Precursors", sub:"Hippocrates · Aristotle · Stoics · Augustine" },
      saussure: { name:"Saussure", sub:"Course in General Linguistics (1916)" },
      peirce: { name:"Peirce", sub:"Anti-Cartesian essays (1868) · Pragmatist essays (1877–78)" },
      hjelmslev: { name:"Hjelmslev", sub:"Prolegomena to a Theory of Language (1943)" },
      eco: { name:"Eco", sub:"Semiotics and the Philosophy of Language (1984)" },
    },
    info: `
      <h2>SemioViz</h2>
      <p class="info-sub">Summarized & Visualized</p>
      <p class="info-tagline">Foundations of Semiotics — From Equivalence to Inference</p>
      <h3>How it works</h3>
      <p>Each <strong>column</strong> represents an author or school of thought. <strong>Cards</strong> are synthesized statements of their thought. Click a card to open details with explanation, diagram and connections to other statements.</p>
      <p>Use the <strong>filters</strong> above to explore by theme. Press <kbd>Esc</kbd> or click outside the panel to close it.</p>
      <div class="legend-row"><span class="legend-swatch" style="background:var(--green)"></span> <span>Agreement or development connection</span></div>
      <div class="legend-row"><span class="legend-swatch" style="background:var(--red)"></span> <span>Critique or opposition connection</span></div>
      <div class="legend-row"><svg class="legend-icon" width="12" height="12" viewBox="0 0 16 16" fill="var(--text-dim)"><rect x="1" y="4" width="5" height="8" rx="1" opacity=".5"/><rect x="8" y="1" width="7" height="14" rx="1" opacity=".7"/></svg> <span>Card contains an explanatory diagram</span></div>
      <h3>The project</h3>
      <p>An interactive map that synthesizes and visualizes the key concepts of structural and interpretive semiotics, following the central thread: the passage from the <strong>restricted model</strong> (the sign as equivalence) to the <strong>enlarged model</strong> (the sign as inference). Approximately 56 synthesized statements with over 90 connections, enriched with didactic examples and diagrams.</p>
      <h3>Contribute</h3>
      <p>SemioViz is an open project: the idea is to start from this core set of authors and expand it over time with new schools and semiotic theories. Contributions, suggestions and corrections are welcome on <a href="https://github.com/stefanocarotenuto/semio-viz" target="_blank" rel="noopener">GitHub</a>.</p>
      <h3>References</h3>
      <div class="refs">
        <div class="ref"><span class="ref-a">F. de Saussure</span><em>Corso di linguistica generale</em><span>(1916). Ed. it. Laterza.</span></div>
        <div class="ref"><span class="ref-a">L. Hjelmslev</span><em>I fondamenti della teoria del linguaggio</em><span>(1943). Ed. it. Einaudi, intr. G.C. Lepschy.</span></div>
        <div class="ref"><span class="ref-a">C.S. Peirce</span><em><a href="https://www.peirce.org/writings/p26.html" target="_blank" rel="noopener">Questions Concerning Certain Faculties Claimed for Man</a></em><span>(1868). Journal of Speculative Philosophy, 2.</span></div>
        <div class="ref"><span class="ref-a">C.S. Peirce</span><em><a href="https://www.peirce.org/writings/p27.html" target="_blank" rel="noopener">Some Consequences of Four Incapacities</a></em><span>(1868). Journal of Speculative Philosophy, 2.</span></div>
        <div class="ref"><span class="ref-a">C.S. Peirce</span><em><a href="https://www.peirce.org/writings/p107.html" target="_blank" rel="noopener">The Fixation of Belief</a></em><span>(1877). Popular Science Monthly, 12.</span></div>
        <div class="ref"><span class="ref-a">C.S. Peirce</span><em><a href="https://www.peirce.org/writings/p119.html" target="_blank" rel="noopener">How to Make Our Ideas Clear</a></em><span>(1878). Popular Science Monthly, 12.</span></div>
        <div class="ref"><span class="ref-a">U. Eco</span><em>Semiotica e filosofia del linguaggio</em><span>(1984). Einaudi. Cap. 1 (Segno e inferenza), 2 (Dizionario vs. Enciclopedia), 5 (Codice).</span></div>
      </div>
      <h3>Inspiration</h3>
      <p>Visualization inspired by <a href="https://www.denizcemonduygu.com/philo/" target="_blank" rel="noopener">History of Philosophy — Summarized & Visualized</a> by Deniz Cem Önduygu.</p>
      <h3>Image credits</h3>
      <p>Author portraits from <a href="https://commons.wikimedia.org/" target="_blank" rel="noopener">Wikimedia Commons</a>, used under their respective licenses: bust of Aristotle (Palazzo Altemps, public domain), portrait of Saussure by F. Jullien (public domain), portrait of Peirce (public domain), portrait of Eco (© Rob Bogaerts / Anefo, CC BY-SA 3.0 NL).</p>
      <p>Typography: Georgia (serif) and system-ui (sans-serif), system fonts.</p>
      <div class="info-credits">
        <p>Design and development: <a href="https://stefanocarotenuto.it" target="_blank" rel="noopener">Stefano Carotenuto</a></p>
        <p>Built with the assistance of <a href="https://claude.com/claude-code" target="_blank" rel="noopener">Claude Code</a> by Anthropic.</p>
        <div class="info-license">
          <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener license">CC BY-NC-SA 4.0</a>
          <p>Free to share and adapt for non-commercial purposes, with attribution and same license.</p>
        </div>
      </div>
      <div class="info-privacy">
        <h3>Privacy & Cookies</h3>
        <p>This website is a static application that runs entirely in the browser. It does not collect personal data, does not use cookies, and does not employ any third-party tracking or analytics services. No data is transmitted to external servers. Browsing is completely anonymous.</p>
      </div>`,

    // Statement translations: { id: { text, detail, tag } }
    stmts: {
      ip1: { tag:"Medical semiotics", text:"Hippocratic medical semiotics reads symptoms inferentially: the body is a text to interpret through clues.", detail:"Semiotics originates as a medical discipline: the physician observes symptoms (natural signs) and infers the disease. <b>Example:</b> yellowish skin (sign) → probable liver disease (inferred meaning). There is no equivalence: the symptom is a starting point for reasoning, not a label. Eco starts here to show that the original model of the sign was inference, not equivalence." },
      ar1: { tag:"Aristotelian equivalence", text:"The linguistic term is equivalent to its definition and fully convertible with it (biconditional).", detail:"Aristotle in the <i>Categories</i> and <i>Topics</i> establishes the equivalence model for linguistic terms: a term is equivalent to its definition by genus and differentia. <b>Example:</b> 'man' = 'rational animal' — fully interchangeable. But this only holds for categorematic terms in assertoric propositions — not for all signs." },
      ar2: { tag:"Rhetorical sign", text:"In the Rhetoric, the sign is always the premise of an inference: tekmerion (necessary) and semeion (defeasible).", detail:"Aristotle, <i>Rhetoric</i> I, 1357a: enthymemes are drawn from probabilities and signs. Two types: <b>Tekmerion</b> (necessary sign): 'if she has milk, then she has given birth' — irrefutable. <b>Semeion</b> (defeasible sign): 'if she breathes heavily, then she has a fever' — other causes possible. Eco notes: the same Aristotle uses 'sign' in opposite ways in the <i>Rhetoric</i> and the <i>De Interpretatione</i>." },
      ar3: { tag:"Sign vs. clue", text:"The verb in De Interpretatione is not a sign of the thing's existence, but a clue (symptom) that an assertion is being made.", detail:"Aristotle, <i>De Interpretatione</i> 16b: the verb 'to be' alone does not affirm existence. Aquinas clarifies: the presence of the verb is <i>evidence, clue, symptom</i> that an assertion is taking place — an inferential/indexical use. <b>Example:</b> saying 'is' in 'Socrates is mortal' does not mean Socrates exists here and now, but signals that something is being predicated." },
      st1: { tag:"Stoic conditional", text:"The Stoic sign is the antecedent of a valid conditional: 'if this smoke, then fire'.", detail:"The Stoics define the sign as the antecedent proposition in a valid conditional, which serves to <i>reveal</i> the consequent. <b>Classic example:</b> 'If there is smoke, then there is fire'. The structure is: if <i>p</i>, then <i>q</i> — where <i>p</i> is the sign and <i>q</i> is the meaning. An inherently inferential model: the sign does not 'equal' the meaning, but implies it." },
      st2: { tag:"Degrees of implication", text:"Stoic implication admits degrees: from necessary equivalence to hypothetical, defeasible signs.", detail:"Sextus Empiricus distinguishes: <b>indicative signs</b> (reveal the unobservable: 'if he sweats, then he has pores' — necessary) and <b>commemorative signs</b> (based on experience: 'if a torch, then enemies' — conventional). A gradient from maximum to minimum strength. <b>Weak example:</b> 'if a man falls into poverty' → has he squandered his wealth? shipwreck? Many possible causes — hypothetical sign, almost abduction." },
      st3: { tag:"Extended Stoic semantics", text:"Every syntactic category has a semantic counterpart: even articles, prepositions, and conjunctions carry meaning.", detail:"The Stoics: complete <i>lekta</i> are composed of incomplete <i>lekta</i>; all have semantic content. Much broader than Aristotle. <b>Example:</b> 'of' in 'Mark's book' expresses a relation of possession — it is not semantically empty. Augustine develops this: 'even prepositions have meaning'." },
      ag1: { tag:"Instructional model", text:"Augustine introduces verbal language among signs and founds the instructional model: the sign instructs someone about something.", detail:"In <i>De Doctrina Christiana</i> (II, 1): the sign is not equivalence but <i>instruction</i>. Augustine distinguishes <b>signa naturalia</b> (smoke→fire, without intention) and <b>signa data</b> (intentional, like words). Crucial move: including verbal language in the general theory of signs. <b>Example:</b> a soldier raises his shield: signum datum to communicate something to his companions." },
      ag2: { tag:"Two levels of the sign", text:"The expression↔content relation seems like equivalence; the proposition→meaning relation is implication. But is this an optical illusion?", detail:"Eco: Augustine passes on to later tradition an unresolved problem — the difference between the denotative relation (word↔meaning, which seems like equivalence) and the inferential relation (the sign as premise of reasoning). 'The first level rests on equivalence, the second on implication.' But Eco suspects that even the first level is secretly inferential." },
      ag3: { tag:"Crystallization", text:"When language becomes the semiotic model par excellence, the sign crystallizes into the 'flat' form of equivalence.", detail:"Gradually, since language is the most analyzable semiotic system, the model of the linguistic sign imposes itself as <i>the</i> model. But by then it is already crystallized in the restricted form: 'encouraged by dictionaries and, unfortunately, by much formal logic' (Eco). <b>The culmination is in Saussure.</b>" },

      sa1: { tag:"Dyadic sign", text:"The linguistic sign is a two-sided psychic entity: signifier (sound-image) and signified (concept).", detail:"It does not unite a thing and a name, but a concept and a sound-image. The two are intimately united: like the <b>recto and verso of a sheet of paper</b> — you cannot cut one without cutting the other. <b>Example:</b> the sign /tree/ does not unite the object tree with the word 'tree', but the concept «tree» with the sound-image /tree/. The sign is a closed domain — and it is this closure that makes it 'restricted' in Eco's reading." },
      sa2: { tag:"Arbitrariness", text:"The bond between signifier and signified is arbitrary: there is no natural connection between the two.", detail:"The idea of 'sister' has no internal connection to the sound sequence <i>s-i-s-t-e-r</i>. It could be any other sequence: proof is that in French it is <i>sœur</i>, in German <i>Schwester</i>. <b>Paradox of arbitrariness:</b> the choice is free (no natural reason), BUT time fixes the choice, making it obligatory. We say <i>man</i> and <i>dog</i> because before us people said <i>man</i> and <i>dog</i>. <b>Arbitrary and differential are two correlative qualities.</b>" },
      sa3: { tag:"Differential value", text:"In language there are only differences, without positive terms: value is purely differential and negative.", detail:"<b>Value ≠ signification.</b> Signification is the internal relation signifier↔signified. Value is the sign's position in the system: a sign is what the others are not. <b>Classic example:</b> Fr. <i>mouton</i> ≠ Eng. <i>sheep</i>/<i>mutton</i> — in French one term covers both the live animal and the meat; in English two distinct terms. <i>Mouton</i> and <i>sheep</i> do not have the same value because the system is different. Value operates on both planes: conceptual and material." },
      sa4: { tag:"System of differences", text:"Language is a system in which all terms are interdependent: the value of one results from the simultaneous presence of the others.", detail:"<b>Chess analogy:</b> as in chess, each piece has value by its position in the game, not by the material it's made of. A wooden knight replaced by an ivory one works the same way, provided it occupies the same position. If a piece is removed, all others change value. Language is not a nomenclature (list of labels on things) but a system of differential relations." },
      sa5: { tag:"Langue / Parole / Langage", text:"Langue is the shared social system; parole is the individual act. Linguistics studies langue.", detail:"<b>Langage</b> (general faculty of language) → too heterogeneous to be a scientific object. It splits into: <b>Langue</b> (social code, 'a treasury deposited by the practice of parole among speakers belonging to the same community', systematic, essential) and <b>Parole</b> (individual act of phonation, combinatorial, accessory). <b>Note:</b> not a rigid dichotomy — they are interdependent." },
      sa6: { tag:"Syntagmatic / Associative", text:"Two axes: syntagmatic (in praesentia, in the chain) and associative (in absentia, in memory). NOT 'paradigmatic'.", detail:"<b>Syntagmatic axis:</b> relations in the speech chain. <i>Un-kind-ness</i>: each element has value by opposition to its neighbours. <b>Associative axis:</b> relations in memory. <i>Teaching</i> evokes: <i>education, learning</i> (by meaning); <i>armament, treatment</i> (by form). <b>CRUCIAL NOTE:</b> Saussure says 'associative', NEVER 'paradigmatic'. The term 'paradigmatic' was introduced by Hjelmslev. Using 'paradigmatic' for Saussure is an anachronism." },
      sa7: { tag:"Semiological project", text:"One can conceive a science of signs within social life: semiology. Linguistics is only a part of it.", detail:"Saussure envisions a 'science that studies the life of signs within social life': <b>semiology</b>. Linguistics would be only a part. <b>Paradox:</b> language, conceived as a special case, ends up becoming the model for all sign systems. Eco calls this the 'blackmail of the linguistic sign': semiology was supposed to free the sign from linguistics, but ended up imposing the linguistic model on all of semiotics." },
      sa8: { tag:"Immutability / Mutability", text:"Immutability: the sign doesn't change by will; mutability: time alters it. Because arbitrary, it knows no law but tradition.", detail:"<b>Immutability:</b> speakers cannot change the sign at will. Four reasons: (1) arbitrary character; (2) multitude of signs; (3) system complexity; (4) collective inertia. <b>Mutability:</b> time, which ensures continuity, also produces alteration — shift of signifier/signified relation. <b>Example:</b> Lat. <i>necare</i> (=to kill) → Fr. <i>noyer</i> (=to drown): the signifier remained similar but the signified shifted." },
      sa9: { tag:"Form, not substance", text:"Language does not create a physical medium for ideas: this combination of thought and sound produces a form, not a substance.", detail:"'The characteristic role of language vis-à-vis thought is not to create a material physical medium for the expression of ideas, but to serve as intermediary between thought and sound.' <b>Air-and-water metaphor:</b> if atmospheric pressure changes, the water surface decomposes into waves — language is like this surface, a zone of articulation between two amorphous masses. <b>'This combination produces a form, not a substance'</b> — a capital phrase for Hjelmslev." },
      sa10: { tag:"Linearity of the signifier", text:"The signifier is linear: it unfolds in time, and this character governs the entire mechanism of language.", detail:"Linearity principle: signifier elements present themselves one after another in the spoken chain, forming a temporal line. You cannot pronounce two phonemes simultaneously. <b>Example:</b> /c-a-t/ unfolds in sequence, not simultaneously. This principle governs syntagmatic organization and distinguishes language from visual semiotic systems (where multiple elements coexist simultaneously)." },

      pe1: { tag:"Anti-intuitionism", text:"We have no faculty of intuition: every cognition is logically determined by previous cognitions.", detail:"<i>Questions Concerning Certain Faculties</i> (1868). First of four anti-Cartesian negations. Against Descartes: there is no immediate, non-inferential knowledge. Every cognition presupposes prior cognitions. <b>Peirce's example:</b> when we enter a room and notice a bad smell, we don't have an 'intuition' of the smell — we have an instantaneous inference based on prior signs. The regress is infinite: there is no 'first' pure thought." },
      pe2: { tag:"Anti-introspection", text:"We have no faculty of introspection: knowledge of the inner world is inferred from external facts.", detail:"Second negation (1868). There is no direct, privileged access to one's own mind. Self-knowledge is mediated by external signs. <b>Peirce's example:</b> a child touching a hot stove: they don't have an 'intuition' of pain as an internal state — they <i>infer</i> their inner state from the perception of contact and bodily reaction. The Cartesian 'cogito ergo sum' is itself an inference, not an intuition." },
      pe3: { tag:"Thought = Sign", text:"We have no power of thinking without signs: thought itself IS intrinsically semiotic.", detail:"Third negation (1868). Thought is not an 'internal' activity that is then 'externally' expressed through signs: <b>thought IS sign</b>. There is no pre-semiotic thought. <b>Example:</b> try to think about the concept of 'justice' without using words, images, symbols: impossible. Even the most abstract thought is constituted by signs. Radical consequence: the mind/language dichotomy is abolished." },
      pe4: { tag:"Anti-incognizable", text:"We have no conception of the absolutely incognizable: what is beyond all possible cognition has no meaning.", detail:"Fourth negation (1868). The Kantian 'noumenon', the thing-in-itself that is absolutely inaccessible, makes no sense as a concept. The real is what inquiry converges towards, not something unknowable in principle. <b>NB:</b> Peirce does not deny the existence of reality — he denies that reality is in principle unknowable." },
      pe5: { tag:"Man is a sign", text:"Man himself is a sign: 'every thought-sign is translated or interpreted in a subsequent one' (CP 5.284).", detail:"<i>Some Consequences of Four Incapacities</i> (1868). '<b>Man is a sign</b>'. Consciousness is not the foundation of experience but a <i>product</i> of the semiotic process. Man is embedded in the flow of semiosis, not an external observer. Consequence: the subject/object dualism is overcome. The 'subject' does not precede the sign: it is constituted by signs." },
      pe6: { tag:"Triadic sign", text:"The sign is a genuine, irreducible triadic relation: representamen, object, interpretant.", detail:"Definition (CP 2.228): 'A sign, or representamen, is something which stands to somebody for something in some respect or capacity.' Three poles: <b>Representamen</b> (the sign-vehicle — the word 'fire', a footprint in snow). <b>Object</b> (what the sign stands for — actual fire, the animal that left the print). <b>Interpretant</b> (the sign's meaningful effect — itself a new sign). The triad cannot be reduced to three dyadic pairs. <b>The interpretant is what is missing in Saussure's model</b> and what makes it 'restricted'." },
      pe7: { tag:"Immediate / Dynamic Object", text:"Immediate Object: how the sign presents the object. Dynamic Object: what stimulates and motivates the sign.", detail:"Crucial distinction. <b>Immediate Object:</b> 'the Object as the sign represents it' — the portion of the object captured by the sign. <b>Dynamic Object:</b> the real object that motivates the sign but that the sign does not exhaust. <b>Example:</b> the word 'water' — the Imm. Obj. is the linguistic concept (H₂O, liquid, transparent…); the Dyn. Obj. is real water in all its inexhaustible complexity. <b>Eco identifies:</b> Imm. Obj. ≈ form of content (Hjelmslev); Dyn. Obj. ≈ matter/continuum." },
      pe8: { tag:"Unlimited semiosis", text:"Semiosis is unlimited: every interpretant is itself a sign that generates new interpretants.", detail:"Every sign, manifesting itself to an interpreter, produces effects (interpretants) that are themselves signs — potentially ad infinitum. <b>Example:</b> the word 'cat' → evokes the image of a cat → 'feline' → 'domestic animal' → 'purrs' → 'worshipped in Egypt'… Each step broadens understanding. It is not a vicious regress: <b>it stops provisionally in habit</b> — but is always reactivatable." },
      pe9: { tag:"Habit", text:"The final logical interpretant is a change of habit: a modification of the disposition to act in certain circumstances.", detail:"Three types of interpretant: <b>(1) Emotional:</b> feeling produced by the sign. <b>(2) Energetic:</b> practical act, individual effort. <b>(3) Logical:</b> general concept — but still a sign, so not final. The only genuinely 'final' interpretant is <b>habit</b>: a change in disposition to act. <b>Example:</b> after learning that fire burns, the habit is the automatic disposition not to touch flame. Habit is not a sign, so it generates no further interpretants — but it is <i>revisable</i>." },
      pe10: { tag:"Pragmatic maxim", text:"The meaning of a concept is identified with the totality of its conceivable practical consequences.", detail:"<i>How to Make Our Ideas Clear</i> (1878). <b>Pragmatic maxim:</b> 'Consider what effects, that might conceivably have practical bearings, we conceive the object of our conception to have. Then, our conception of these effects is the whole of our conception of the object.' Three degrees of clarity: (1) familiarity of use, (2) abstract definition, (3) understanding of practical consequences. <b>Peirce's example:</b> what does 'hard' mean? Not an abstract definition, but: 'it will not be scratched by many other substances'." },
      pe11: { tag:"Real vs. paper doubt", text:"Real doubt arises from genuine irritation, not from method: one cannot doubt everything by decision.", detail:"<i>The Fixation of Belief</i> (1877). Against Cartesian doubt (fictitious, 'paper doubt'): one cannot truly doubt everything — one doubts only what one has positive reason to doubt. <b>Example:</b> 'I could not doubt that this is my hand' — Cartesian universal doubt is not a genuine psychological state but a methodological artifice. Inquiry starts from <b>genuine irritation of doubt</b> and aims at <b>fixation of belief</b>." },
      pe12: { tag:"Fixation of belief", text:"Four methods of fixation: tenacity, authority, a priori, scientific. Only the last is reliable.", detail:"(1) <b>Tenacity:</b> clinging to one's opinion. (2) <b>Authority:</b> trusting an institution. (3) <b>A priori:</b> pure reasoning, but based on 'intellectual tastes'. (4) <b>Scientific:</b> only method that submits hypotheses to the test of external reality. <b>Only the scientific method works long-term</b> because it presupposes a 'real' independent of individual opinions. Truth is the ideal limit toward which the community of inquirers converges." },
      pe13: { tag:"Icon / Index / Symbol", text:"Icon (similarity), index (causal connection), symbol (convention): no sign is purely one type alone.", detail:"Tripartition by relation to Object. <b>Icon:</b> similarity with the object (portrait, map, onomatopoeia). <b>Index:</b> causal/existential connection (smoke→fire, weathervane→wind, footprint→animal). <b>Symbol:</b> convention or law (words, traffic signs, chemical formulas). <b>Crucial:</b> no actual sign is purely one — it contains elements of all three in varying proportions. <b>TERMINOLOGICAL NOTE:</b> Peircean 'symbol' (conventional) is the opposite of Saussurean 'symbol' (motivated)." },
      pe14: { tag:"Abduction", text:"Abduction is hypothetical inference: I observe a surprising fact and hypothesize a law to explain it.", detail:"Beyond deduction and induction, Peirce introduces <b>abduction</b>: the process by which a hypothesis is generated. Schema: I observe a surprising <b>Result</b> → I hypothesize a <b>Law</b> → the fact becomes a <b>Case</b> of that law. <b>Medical example (Eco):</b> I observe red spots on the skin (Result) → I hypothesize 'measles' (Law) → the spots are a Case of measles. It is the engine of scientific discovery and interpretation of weak signs." },

      hj1: { tag:"Principle of immanence", text:"'A totality does not consist of things but of relationships': linguistics must describe language as a self-sufficient structure.", detail:"<b>Principle of immanence.</b> Language must be studied as form, not substance. 'To postulate objects as something other than the terms of relationships is a superfluous axiom.' The theory must be: (1) <b>coherent</b> (non-contradictory), (2) <b>exhaustive</b> (account for all data), (3) <b>as simple as possible</b> (empirical principle). Not a rejection of external reality but a methodological priority." },
      hj2: { tag:"Sign function", text:"A semiotics is a sign function contracted by two functives: the expression plane and the content plane.", detail:"The two planes are <b>solidary</b> (interdependent): no expression without content, no content without expression. The <b>sign function</b> is the relation that unites them. <b>Example:</b> the word /cat/: the expression plane is the sound sequence [c-a-t]; the content plane is the concept 'small domestic feline'. Neither can be analyzed without the other." },
      hj3: { tag:"Form of content", text:"The form of content is the network of differential relations that each language projects onto the amorphous matter of experience.", detail:"As the sound continuum is segmented into phonemes by the form of expression, so the continuum of experience is segmented by the <b>form of content</b>. <b>Colour example:</b> the same spectral zone is divided into 4 terms by English (<i>green, blue, gray, brown</i>) and 3 by Welsh (<i>gwyrdd, glas, llwyd</i>). Same matter → different forms → different substances. <b>Kinship example:</b> It. <i>fratello/sorella</i> (2 terms); Chinese: <i>xiōng/dì/zǐ/mèi</i> (4 terms); Malay: <i>saudara</i> (1 term). <b>NOT semantics</b>: it is the internal differential structure, not meaning." },
      hj4: { tag:"Quadripartition", text:"Matter (amorphous continuum), form (differential network), substance (formed matter). Substance presupposes form.", detail:"<b>Hjelmslevian quadripartition:</b> for each plane (expression and content): <b>Matter</b> (<i>mening</i>, <i>purport</i>): the amorphous continuum, identical across languages. <b>Form:</b> the network of oppositions and differential relations. <b>Substance:</b> matter once formed — the result of projecting form onto matter. <b>Substance presupposes form, not vice versa:</b> given a form, it can manifest in any substance; but given a substance, it is necessarily the manifestation of a form." },
      hj5: { tag:"Commutation", text:"Commutation test: if exchange on one plane causes a corresponding exchange on the other, the two elements are invariants.", detail:"Empirical criterion for distinguishing <b>invariants</b> (pertinent units) from <b>variants</b>. <b>Expression example:</b> /p/in → /b/in: content changes → /p/ and /b/ are distinct phonemes (invariants). <b>Variant example:</b> rolled /r/ vs. uvular /r/ in 'Roma': content unchanged → variants of the same phoneme. The test is <b>reversible</b> (works from content to expression too) and requires substance for verification." },
      hj6: { tag:"Figures / Non-signs", text:"Signs are analyzed into figures (non-signs): phonemes on expression, semes/pleremes on content.", detail:"<b>Figures</b> are the minimal elements without meaning of their own, which compose signs. <b>Expression:</b> phonemes. /p/, /a/, /n/ compose the sign 'pan' but are not signs themselves. <b>Content:</b> semes (pleremes). 'bovine + male' = <i>bull</i>; 'bovine + female' = <i>cow</i>; 'equine + male' = <i>stallion</i>. <b>Key difference:</b> for signs, same expression difference = same content difference; for figures, same expression difference → different content changes. Figures enable the <b>economy of the system</b>: a limited number of figures → infinite signs." },
      hj7: { tag:"Denotation / Connotation", text:"Connotative semiotics has an entire denotative semiotics as its expression plane. Metasemiotics has a semiotics as its content.", detail:"<b>Denotative semiotics:</b> the base system (expression + content in sign function). <b>Connotative semiotics:</b> the entire denotative sign becomes the expression plane of a further content. <b>Example:</b> 'steed' (denotative sign: signifier /steed/ + signified 'horse') → as a complete sign becomes expression of: 'archaism, literariness, high register'. <b>Metasemiotics:</b> language about language (linguistics is a metasemiotics). <b>HISTORICAL NOTE:</b> Hjelmslev, <i>Prolegomena</i> ch. 22 (1943), NOT Barthes." },
      hj8: { tag:"Form, not substance", text:"Language is a form, not a substance. Differences between languages are differences of form, not material substance.", detail:"'The differences between languages are not based on different realizations of a single type of substance, but on different realizations of a <b>principle of formation</b>.' <b>Example:</b> the vowel continuum — Lak (Caucasian) has 3 vowels, Spanish 5, Italian 7: same sound matter, different forms. Consequence: 'phonetic types of general validity or eternal schemes of ideas cannot be constructed empirically'." },
      hj9: { tag:"Biplanarity / Non-conformity", text:"The two planes are non-conformal: there is no one-to-one correspondence between expression and content functives.", detail:"<b>Non-conformity:</b> the condition for operating with two planes. If there were isomorphism (conformity), a single plane would suffice. <b>Example:</b> Latin <i>-ibus</i>: 4 expression elements (<i>i, b, u, s</i>) but only 2 content elements ('dative/ablative' + 'plural'). No biunivocal relation. Languages are <b>biplanar and non-conformal</b> — that's why they have figures." },
      hj10: { tag:"Symbolic in Hjelmslev", text:"Hjelmslev calls 'symbolic' the uniplanar systems where expression is isomorphic to content (chess, diagrams).", detail:"For Hjelmslev, <b>symbolic</b> systems are those where expression is isomorphic to content: 'entities that are depictions or emblems, like Thorvaldsen's Christ as symbol of compassion, the hammer and sickle as symbol of communism, the scales as symbol of justice.' <b>Chess too</b> is symbolic for Hjelmslev: uniplanar. <b>Terminological confusion:</b> Saussure's 'symbol' is the motivated sign; Peirce's 'symbol' is conventional; Hjelmslev uses it for uniplanar systems." },

      ec1: { tag:"Restricted → Enlarged", text:"The sign, wrongly reduced to the 'restricted' model of equivalence, must be rediscovered in the 'enlarged' model of inference.", detail:"<b>Central thesis</b> of <i>Semiotics and the Philosophy of Language</i>, ch. 1 (Sign and Inference). The sign as bidirectional equivalence (signifier ↔ signified) is a historical reduction. <b>The original model</b> — from Hippocrates (medical semiotics) to the Stoics (conditional) to Augustine (instructional model) — was <b>inferential</b>." },
      ec2: { tag:"Historical reconstruction", text:"The inferential model was the ORIGINAL one: the reduction to equivalence is a historical effect of linguistic crystallization.", detail:"<b>Eco's historical reconstruction:</b> Hippocrates (inferential reading of symptoms) → Aristotle (in the Rhetoric, sign = enthymeme premise) → Stoics (sign = conditional antecedent) → Augustine (instructional model). Crystallization into equivalence happens when the linguistic sign imposes itself as the model par excellence. Eco shows it is <b>legitimate to reformulate</b> the sign as enlarged because the enlarged model was the original." },
      ec3: { tag:"Criterion of interpretance", text:"The sign always opens to something else: no interpretant fails to shift, however slightly, the boundaries.", detail:"<b>Criterion of interpretance</b> (from Peirce): every interpretant not only retranslates the immediate object but broadens its understanding. 'There is no interpretant that, in matching the sign it interprets, does not shift its boundaries at least slightly.' <b>Eco's example:</b> I say /father/ → the term defines a two-argument predicate → if father, then someone who is this father's child → an argumentative topic opens up." },
      ec4: { tag:"Interpretation as definition", text:"To interpret a sign = to define the portion of content conveyed, in its relations to other portions.", detail:"'To interpret a sign means to define the portion of content conveyed, in its relations to the other portions derived from the global segmentation of content.' Interpretation is translation into other signs. <b>Radical possibility:</b> if interpretation is carried far enough, it can put in crisis the <b>segmentation itself</b> — the way the form of content has segmented the continuum." },
      ec5: { tag:"Integration Hj + Pe", text:"Hjelmslev describes the FORM of the sign; Peirce explains how that form GENERATES meaning. Integration, not alternative.", detail:"<b>Eco's crucial integration:</b> not Hjelmslev OR Peirce, but Hjelmslev <b>AND</b> Peirce. Hjelmslev provides the <b>structure</b> (form of content: how the system segments the continuum). Peirce provides the <b>process</b> (unlimited semiosis: how meaning is generated and expands through interpretants). <b>The encyclopedia is the meeting point:</b> rhizomatic structure (form) traversed by interpretive processes (semiosis)." },
      ec6: { tag:"Continuum = Dynamic Object", text:"Hjelmslev's continuum = Peirce's Dynamic Object: what motivates the sign but the sign doesn't immediately account for.", detail:"<b>Decisive reformulation:</b> Matter/continuum (Hjelmslev) = Dynamic Object (Peirce): the real that stimulates sign production. Form of content = Immediate Object: how the sign presents that object. 'A given civilization organizes content into fields, axes, subsystems, not always coherent.' <b>Semiotic meaning is tied to cognitive meaning:</b> to know is to segment the continuum through signs." },
      ec7: { tag:"Dictionary vs. Encyclopedia", text:"DICTIONARY: closed tree (genus + differentia). ENCYCLOPEDIA: open network of interpretants, limited by habit.", detail:"<b>Dictionary:</b> Porphyrian tree / Katz & Fodor. 'Bachelor' = [+human, +male, +adult, +unmarried]. Problems: (1) semes are words → infinite regress; (2) cannot account for encyclopedic knowledge. <b>Encyclopedia:</b> rhizomatic network, potentially infinite. <b>Example:</b> encyclopedic knowledge of 'cat': purrs, hunts mice, was worshipped in ancient Egypt, stars in internet memes — none of this fits in a dictionary of necessary and sufficient conditions." },
      ec8: { tag:"Encyclopedia as postulate", text:"The encyclopedia integrates Hjelmslevian form (structure) with Peircean process (semiosis). It's a postulate, not an object.", detail:"The encyclopedia is not a bigger dictionary — it is a <b>different theoretical model</b>. It integrates Hjelmslev's form of content (the network of differences structuring meaning) with Peirce's unlimited semiosis (the process by which each interpretant generates others). <b>It does not exist in its totality:</b> it is the whole of possible interpretations, pragmatically limited by Peircean habit and social negotiation." },
      ec9: { tag:"Code: inverted symmetry", text:"For the CODE, the original model WAS the restricted one. Reformulation as enlarged is a 'new and arbitrary baptism'.", detail:"<b>Inverted symmetry</b> with respect to the sign (ch. 3): for the sign, the enlarged (inferential) model was original → must be <i>rediscovered</i>. For the code, the restricted (correlational) model was original → enlargement is a <i>new baptism</i>. Three historical senses of 'code': <b>paleographic</b> (codex, tree trunk → book), <b>correlational</b> (Morse code), <b>institutional</b> (civil code: system of norms)." },
      ec10: { tag:"Cryptographic code", text:"The cryptographic code is the pure model of equivalence: if every sign were like this, it would be THE semiotic model.", detail:"The cryptographic code establishes 'relations of absolute equivalence between expression and content.' <b>Example:</b> Abbot Trithemius's code (1499): A='Annuncidi', B='Sempre', C='Mondo senza fine'… — total biunivocal correspondence. <b>But:</b> 'if the sign is based on inference and is the starting point for an indefinite process of interpretation, then the cryptographic model does not define the life of semiotic systems.'" },
      ec11: { tag:"Strong / weak codes", text:"Strong codes (stable correlation) and weak codes (unstable, abductive): gradient from restricted to enlarged.", detail:"The gradient runs from maximum to minimum strength. <b>Strong code:</b> stable correlation, quasi-equivalence. <i>Example:</i> Morse code, traffic signs. <b>Weak code:</b> unstable, hypothetical, abductive. <i>Example:</i> medical symptoms, detective clues. <b>Eco notes</b> that the notion of code progressively dissolves into encyclopedia as the strength weakens." },
      ec12: { tag:"Ratio facilis / difficilis", text:"Ratio facilis: preformed expressive type. Ratio difficilis: expressive type modeled on the content type.", detail:"Eco proposes not a typology of signs but of <b>modes of sign production</b>. <b>Ratio facilis:</b> the expressive type is preformed, arbitrarily correlated to content. <i>Example:</i> the word 'horse' doesn't look like a horse. <b>Ratio difficilis:</b> lacking a preformed type, expression is modeled on content. <i>Example:</i> a railway diagram that projects spatial relations between cities. A real sign usually combines <b>multiple production modes</b>." },
      ec13: { tag:"Ambiguity of 'symbol'", text:"Peircean 'symbol' (conventional) ≠ Saussurean 'symbol' (motivated) ≠ Hjelmslevian 'symbolic' (uniplanar).", detail:"Three irreducible uses of the same term: <b>Peirce:</b> symbol = sign by convention/law (words, signals). <b>Saussure:</b> symbol = not entirely arbitrary sign, with residual natural link (the scales of justice 'are not entirely arbitrary'). <b>Hjelmslev:</b> symbolic = uniplanar isomorphic system (chess, diagrams, emblems). Eco reconstructs this 'network of family resemblances'." },
      ec14: { tag:"Modes of sign production", text:"Traces, symptoms, clues: modes of sign production with varying degrees of ratio and codification.", detail:"<b>Traces/imprints:</b> governed by ratio difficilis — the imprint 'says that, given a configuration on an impressible surface, then a given class of impressing agents.' <i>Example:</i> a footprint in snow → class of animals. <b>Symptoms:</b> governed by ratio facilis <i>when already codified</i> (the symptom is recognized within the medical system) — refer to a cause by codified experience. <i>Example:</i> high fever + spots → measles. But a not-yet-codified symptom is closer to ratio difficilis and abduction. The table of modes does not classify signs but <b>productive processes</b>." },
      ec15: { tag:"Connotation vs. Semiosis", text:"Hjelmslevian connotation (systemic stratification) differs from Peircean semiosis (processual dynamics), but Eco integrates both.", detail:"<b>Hjelmslev:</b> connotation is a <i>static</i> stratification of semiotic levels. <b>Peirce:</b> semiosis is a <i>dynamic</i> process of interpretant generation. <b>Eco integrates both:</b> connotation describes <i>how systems stack</i>; semiosis describes <i>how meaning is generated</i>. No contradiction: they are two complementary perspectives on the same phenomenon." },
      ec16: { tag:"Unitary structure of the sign", text:"There is no structural difference between first and second level: what changes is the strength of the if/then.", detail:"Between denotation and connotation, between strong and weak code: what changes is the <b>degree of epistemological necessity</b> of the 'if…then', not the structure of the sign. 'There is no difference in semiotic structure between first- and second-level signification.' The sign is always inferential: more or less cogent, but structurally unitary. <b>This is Eco's final unification:</b> one semiotic model with a gradient of strength." },
    }
  }
};
